### ISSUE TITLE
How to increase bar width in the OneLine version?

### ISSUE THREAD

**Issue by realaltffour** [migueravila/SimplerentFox#25]
Title.

On librewolf, using containers, the titlebar need to be extended. I've looked into the userChrome.css, it's not intuitive for me.

Any help would be much appreciated.

**Comment by Dynexyst** [comment]
Facing a similar issue, I want to decrease the size of the URL bar. (Default max width seems to be 430px, I'd prefer if it was around 300px or so. Might need to experiment to find a good size, but can't since it wont budge no matter where i throw width rules in the css.)

**Comment by migueravila** [comment]
Hey @realaltffour, thanks to @Dynexyst we now have a variable called `--urlbar-width`  and you can play with that value in order to get the right size for you (Maybe 30 - 35 will do for you)
