### ISSUE TITLE
Colors broken

### ISSUE THREAD

**Issue by Dev380** [migueravila/SimplerentFox#29]
All my tabs have colors working fine, except for the tab I am currently on, which has the default colors. How do I change this? Thanks.
![Screenshot-20210321110800-510x62](https://user-images.githubusercontent.com/49997896/111909972-4a673e00-8a57-11eb-8718-54800255c4ee.png)

**Comment by migueravila** [comment]
Hey! @Dev380 Have you tried checking out if it's the theme you have? By default SimplerentFox is made to use some colors. Also the tabs colors (font and background) are managed by your color theme installed on Firefox by the add-ons store. Check if changing your theme to another one helps (This one helps as a complement of SimplerentFox: https://addons.mozilla.org/en-US/firefox/addon/simplerentfox/)

**Comment by Dev380** [comment]
Oh, I forgot to close this issue, it was the theme and I solved it by changing the tab[selected] css color attribute.
